version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"

  backend:
    build:
      context: .  # Update this line
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://db:27017/mernstack

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
