name: CI/CD for MERN Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install Dependencies and Build Backend
      - name: Install Backend Dependencies
        run: |
          npm install
          npm run build

      # Step 4: Build and Push Docker Images
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

      # Step 5: Set up SSH for EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 6: Deploy on EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

          # Stop and remove old containers
          docker stop mern-backend || true
          docker rm mern-backend || true
          docker stop mern-frontend || true
          docker rm mern-frontend || true

          # Run new containers
          docker run -d --name mern-backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker run -d --name mern-frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          EOF
