name: CI/CD for MERN Stack with Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest -f ./backend/Dockerfile ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

      # Step 4: Build and Push Frontend Docker Image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

      # Step 5: Set up SSH for Deployment to EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 6: Deploy on EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          
          # Pull Docker Images
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          
          # Stop and Remove Old Containers
          docker stop mern-backend || true
          docker rm mern-backend || true
          docker stop mern-frontend || true
          docker rm mern-frontend || true
          docker stop mern-database || true
          docker rm mern-database || true

          # Start Database (MongoDB)
          docker run -d --name mern-database -p 27017:27017 -v mongo-data:/data/db mongo:latest
          
          # Wait for the Database to Be Ready
          sleep 10
          
          # Start Backend Container
          docker run -d \
            --name mern-backend \
            -p 5000:5000 \
            --env-file /path/to/backend/.env \
            ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          
          # Start Frontend Container
          docker run -d \
            --name mern-frontend \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          EOF
